image:
  repository: registry.singleportal.opsta.in.th/mel/crypto-store-frontend
  tag: latest
imagePullSecret:
  - registy-mel
resources:
    limits:
      cpu: "2000m"
      memory: "2000Mi"
    requests:
      cpu: "200m"
      memory: "500Mi"
containerPort: 3000
probe:
  enabled: true
  path: "/health"
  settings:
    initialDelaySeconds: 30 
