import { Inter, Prompt } from "next/font/google";
import "@/styles/globals.css";
import Footer from "@/components/global/Footer";
const inter = Inter({ subsets: ["latin"] });
const prompt = Prompt({
  subsets: ["latin"],
  variable: "--font-prompt",
  weight: ["400", "600"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${prompt.variable} font-sans`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
