services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
        - ./frontend/:/home/node/
    ports:
      - "3000:3000"
    user: 1000:1000
    depends_on:
      - backend
    command: sh -c "npm install && npm run dev"
      
  backend:
    tty: true
    build: 
      context: .
      dockerfile: backend/Dockerfile
    volumes:
    - ./backend/:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=hello_django_dev
      - DB_USER=hello_django
      - DB_PASSWORD=hello_django
    command: "python manage.py runserver 0.0.0.0:8000"


  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
    driver: local