services:
  kc:
    image: postgres:15
    volumes:
      - postgres_keycloak:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: melisconfused

  keycloak:
    # container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0
    environment:
      # keycloak settings
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: INFO
      ROOT_LOGLEVEL: INFO
      # database
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://kc:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: melisconfused
    ports:
      - "8080:8080"
    depends_on:
      - kc
    command: start-dev
    
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
        - ./frontend/:/home/node/
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    user: 1000:1000
    depends_on:
      # - keycloak
      - backend
    # environment:
    #   - NODE_OPTIONS=--dns-result-order=ipv4first
    command: sh -c "npm install && npm run dev"
      
  backend:
    tty: true
    build: 
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=hello_django_dev
      - DB_USER=hello_django
      - DB_PASSWORD=hello_django
    command: "python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
    driver: local
  postgres_keycloak:
    driver: local

networks:
  keycloak-network:
    driver: bridge