# Generated by Django 5.0.3 on 2024-04-12 08:40

import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cartitem_usercart_delete_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercart',
            options={},
        ),
        migrations.AlterModelManagers(
            name='usercart',
            managers=[
                ('items_in_cart_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='usercart',
            name='user_id',
            field=models.IntegerField(default=uuid.uuid4),
        ),
    ]
