# Generated by Django 5.0.3 on 2024-04-12 09:17

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_usercart_options_alter_usercart_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelManagers(
            name='cartitem',
            managers=[
                ('items_in_cart_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='usercart',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='user_cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.usercart'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
