# Generated by Django 5.0.3 on 2024-04-12 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_cartitem_options_alter_cartitem_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='total_stock',
            new_name='quantity_on_hand',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='usable_cart_price',
            new_name='minimum_cart_price',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='usable_cart_quanity',
            new_name='minimum_cart_quanity',
        ),
        migrations.AlterField(
            model_name='usercart',
            name='selected_promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.promotion'),
        ),
    ]
